modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="createirrigation"
version="0.2"
displayName="Create Irrigation"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/create-irrigation"
#logoFile="logo.png"
#credits=""
authors="StephenBarnes"
description='''
Tools for irrigating farmland using the Create mod'''

[[dependencies.createirrigation]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.createirrigation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.createirrigation]]
	modId = "create"
	mandatory = true
	versionRange = "[v0.3.2f,)"
	ordering = "AFTER"
	side = "BOTH"

[[dependencies.createirrigation]]
    modId="flywheel"
    mandatory=true
    versionRange="[1.16-0.2.3,1.16-0.3)"
    ordering="AFTER"
    side="BOTH"

#[[dependencies.createirrigation]]
#	modId = "createautomated"
#	mandatory = false
#	versionRange = "[1.0.0,)"
#	ordering = "AFTER"
#	side = "BOTH"